version: 2

project_name: hyperstream

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: hstream
    main: ./main.go
    binary: hstream_{{ .Os }}_{{ .Arch }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: binary

checksum:
  name_template: checksums.txt
